---
title: "Preparação de dados - Ação 6.1"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
# options
options(timeout = 1e6)
sf::sf_use_s2(FALSE)
```

## Atlantic-Camtraps

### Importar locations
```{r}
# import sites
ca_si <- readr::read_csv(
    "data/data_papers/ATLANTIC_CAMTRAPS_1-0_LOCATION.csv"
    ) %>%
    # select only id and coordinates
    dplyr::select(
        location_id, X, Y
        )
#ca_si
```

### Import surveys
```{r}
# import sites names
ca_si_na <- readr::read_csv(
    "data/data_papers/ATLANTIC_CAMTRAPS_1-0_SURVEY.csv"
    ) %>%
    # join sites names with coordinates
    dplyr::left_join(
        .,
        ca_si,
        by = "location_id"
        ) %>%
    # select only ids, year and coordinates
    dplyr::select(
        study_id, location_id, survey_id, yearfinish,  X, Y
        )
ca_si_na
```

```{r}
# import study
ca_st_na <- readr::read_csv(
    "data/data_papers/ATLANTIC_CAMTRAPS_1-0_STUDY.csv"
    ) %>% 
    dplyr::left_join(
        ., ca_si_na, by = "study_id"
        ) %>% 
    dplyr::select(
        location_id, survey_id, yearfinish,  X, Y, study
        )
ca_st_na
```

### Importar os nomes das espécies

```{r}
# import species names
ca_sp_na <- readr::read_csv(
    "data/data_papers/ATLANTIC_CAMTRAPS_1-0_SPECIES.csv"
    ) %>%
    # remove unnecessary columns
    dplyr::select(
        order:genus, species_name, species_code
        )
#ca_sp_na

```

### Importar registros
```{r}
# import records
ca_sp <- readr::read_csv(
    "data/data_papers/ATLANTIC_CAMTRAPS_1-0_RECORDS.csv"
    ) %>% 
    # remove unnecessary columns
    dplyr::select(
        survey_id, species_code, presence_absence
        ) %>% 
    # remove absences
    dplyr::filter(
        presence_absence == 1
        ) %>% 
    # correction of Potus flavus
    dplyr::mutate(
        species_code = ifelse(
            species_code == "Potu_flav", "Poto_flav", species_code
            )
        ) %>% 
    # join with taxonomy information
    dplyr::left_join(
        ., ca_sp_na, by = "species_code"
        ) %>% 
    # remove unnacessary columns
    dplyr::select(
        -c(
            presence_absence,  species_code
            )
        )
#ca_sp
```

### Integrar informações
```{r}
# join spatial data
ca_occ <- ca_sp %>% 
    dplyr::left_join(
        ca_st_na, by = "survey_id"
        ) %>% 
    # rename columns
    dplyr::mutate(species = species_name,
                  longitude = as.numeric(X), 
                  latitude = as.numeric(Y), 
                  year = as.numeric(yearfinish),
                  source = "atlantic_camtrap") %>%
    #remove unnecessary columns
    dplyr::select(
        order:genus, species, longitude, latitude, year, source, study
        ) %>% 
    # add id
    tibble::rowid_to_column()
#ca_occ
```

### Exportar
```{r}
# export data
readr::write_csv(ca_occ, "data/atlantic_camtrap.csv")
```

## Atlantic Large Mammals

### Importar dados
```{r}
# import data
lm_occ <- readr::read_csv(
    "data/data_papers/ATLANTIC_MAMMAL_MID_LARGE _assemblages_and_sites.csv"
    ) %>% 
    dplyr::mutate(
        genus = str_split(Actual_species_Name, " ", simplify = TRUE)[, 1],
        species = Actual_species_Name,
        longitude = as.numeric(Longitude), 
        latitude = as.numeric(Latitude), 
        year = as.numeric(Year_finish),
        study = Reference, 
        source = "atlantic_large_mammals"
        ) %>%
    dplyr::select(
        genus, species, longitude, latitude, year, source, study
        ) %>% 
    tidyr::drop_na(
        longitude, latitude
        ) %>% 
    dplyr::mutate(
        species = str_trim(species)
        ) %>% 
    tibble::rowid_to_column() %>% 
    dplyr::left_join(
        .,
        rbind(
            unique(
                ca_occ[, c(2, 3, 4)]
                )
            ),
        by = "genus"
        ) %>% 
    dplyr::relocate(
        order:family,
        .before = 2
        )
lm_occ
```

### Exportar
```{r}
# export data
readr::write_csv(lm_occ, "data/atlantic_large_mammals.csv")
```

## Neotropical Carnivores

### Importar dados
```{r}
# import
neo_car_occ <- readr::read_csv("data/data_papers/NEOTROPICAL_CARNIVORES_DATASET_2020-04.csv")
```

### Filtrar registros duvidosos
```{r}
neo_car_occ <- neo_car_occ[!grepl("Informal interview", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Interview", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Scratch", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Sign", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Scat", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Vocalization", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Track", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Sighting", neo_car_occ$TYPE_REC),]
neo_car_occ <- neo_car_occ[!grepl("Literature review", neo_car_occ$TYPE_REC),]

sort(unique(neo_car_occ$TYPE_REC))

#Precisa resolver o sinal em alguns anos
#sort(unique(neo_car_occ$COL_END_YR))

neo_car_occ <- neo_car_occ %>%
    dplyr::mutate(family = FAMILY,
                  genus = GENUS,
                  species = SPECIES,
                  name = SPECIES, 
                  longitude = LONG_X, 
                  latitude = LAT_Y,
                  year = as.numeric(COL_END_YR),
                  study = REFERENCE,
                  source = "neotropical_carnivores") %>%
    dplyr::select(
        family, genus, species, longitude, latitude, year, source, study
        ) %>% 
    dplyr::mutate(
        species = str_trim(species)
        ) %>% 
    tibble::rowid_to_column() %>% 
    dplyr::left_join(
        .,
        unique(
            rbind(
                ca_occ[, c(2, 4)],
                lm_occ[, c(2, 4)]
                )
            ),
        by = "genus"
        ) %>% 
    dplyr::relocate(
        order, .after = 1
        )
neo_car_occ
```

### Exportar
```{r}
# export data
readr::write_csv(neo_car_occ, "data/neotropical_carnivores.csv")

```

## GBIF
```{r}
# remove columns that only contain NA values
not_all_na <- function(x) any(!is.na(x))

gbif_lp <- readr::read_tsv(
    "data/GBIF_leopardusPardalis/verbatim.txt"
    ) %>%
    # filter data without coordinates
    dplyr::filter(
        !is.na(decimalLatitude)
    ) %>%
    dplyr::filter(
        !is.na(decimalLongitude)
    ) %>%
    # filter data from Brazil
    dplyr::filter(
        country == "Brasil" | country == "Brazil"
    ) %>%
    dplyr::filter(
         year > 1999 & basisOfRecord == "Occurrence"
    ) %>%
    dplyr::mutate(
        species = scientificName,
        longitude = decimalLongitude,
        latitude = decimalLatitude,
        source = "GBIF.org",
        study = "GBIF.org (16 December 2022) GBIF Occurrence Download https://doi.org/10.15468/dl.9cen59"
    ) %>%
    # remove columns that only contain NA values
    dplyr::select(
        where(not_all_na)
    ) %>%

    dplyr::select(
        family, genus, species, longitude, latitude, year, source, study
    )
```