---
title: "Organização e limpeza - Ação 6.1"
output: html_notebook
---

```{r}
# carregar dados do Atlantic Large Mammals
at_lar <- readr::read_csv("data/atlantic_large_mammals.csv")
at_lar

# Carregar dados do Atlantic Camtraps
at_cam <- readr::read_csv("data/atlantic_camtrap.csv")
at_cam

# Carregar dados do Neotropical Carnivores
neo_car <- readr::read_csv("data/neotropical_carnivores.csv")
neo_car

# Junte os dados
occ <- dplyr::bind_rows(
  at_cam,
  at_lar,
  neo_car
  ) %>%
  # Selecione apenas os campos de interesse sem repetição
  dplyr::select(-1) %>% 
    dplyr::distinct(species, longitude, latitude, .keep_all = TRUE)
occ

```


```{r}
# vetor
occ_v <- occ %>% 
    tidyr::drop_na(longitude, latitude) %>% 
    dplyr::mutate(lon = longitude,
                  lat = latitude) %>% 
    dplyr::filter(lon > -180 & lon < 180) %>% 
    dplyr::filter(lat > -90 & lat < 90) %>% 
    sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)
occ_v

plot(occ_v$geometry, pch = 20)

```

```{r}
mamiferos <- occ_v
mamiferos <- mamiferos %>%
  dplyr::filter(
    family == "Felidae"
  )

mamiferos <- mamiferos[!grepl("sp.", mamiferos$species),]

mamiferos <- mamiferos[!grepl("Panthera onca", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Puma concolor", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Felis catus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Lynx rufus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Leopardus guigna", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Leopardus jacobita", mamiferos$species),]
mamiferos$species <- gsub("Puma yagouaroundi","Herpailurus yagouaroundi",
                          mamiferos$species)
sort(unique(occ_v$species))
sort(unique(mamiferos$species))
plot(mamiferos$geometry, pch = 20)

```

```{r}
jaguarundi <- occ_v

jaguarundi$species <- gsub("Puma yagouaroundi","Herpailurus yagouaroundi",
                          jaguarundi$species)

jaguarundi <- jaguarundi %>%
  dplyr::filter(
    species == "Herpailurus yagouaroundi"
  )

sort(unique(jaguarundi$species))
plot(jaguarundi$geometry, pch = 20)

```

```{r}
# export data
readr::write_csv(jaguarundi, "data/herpailurusYagouaroundi.csv")

```




```{r}
brasil <- sf::st_read("data/geodata/vetor_EstadosBR_LLWGS84/EstadosBR_IBGE_LLWGS84.shp")

gatosBrasil <- mamiferos[brasil, ] %>% 
  tibble::rowid_to_column()

plot(gatosBrasil$geometry, pch = 20)

gatosBrasil$genus <- word(gatosBrasil$species,1)

unique(sort(gatosBrasil$species))

unique(sort(gatosBrasil$genus))

unique(sort(gatosBrasil$family))

unique(sort(gatosBrasil$order))

gatosBrasil <- gatosBrasil %>%
  filter(year>1999)


```

```{r}
# export data
readr::write_csv(gatosBrasil, "data/gatosBrasil.csv")


```

