---
title: "Mamíferos de São Paulo"
author: "Fernando Lima, D.Sc."
output: html_notebook
---

Limpeza de dados para lista de espécies de mamíferos terrestres. Dados brutos integrados por Maurício Vancine.

Dados de entrada e saída desse script disponíveis no [Github](https://github.com/pardalismitis/mamiferosDeSaoPaulo).

```{r}
rm(list = ls(all = TRUE))
library(here)
library(stringr)
library(dbplyr)
```

Leitura e checagem
```{r}
mamiferos = 
  read.csv("occ_v_sp.csv",
           #sep = ";",
           na.strings = c("", "NA"),
           encoding = "UTF-8"
  )

unique(sort(mamiferos$species))
```

Exclusão de registros nada a ver.
```{r}
mamiferos <- mamiferos[!grepl("sp.", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Monodelphis americana/scalops", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Callithrix jacchus X Callithrix aurita", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Callithrix jacchus X Callithrix penicillata", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Callithrix penicillata x Callithrix aurita", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Unidentified rodent", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Dasyprocta iacki", mamiferos$species),]
```

Correção de taxonomia
```{r}
mamiferos$species <- gsub("Puma yagouaroundi","Herpailurus yagouaroundi",
                     gsub("marmosops paulensis","Marmosops paulensis",
                     gsub("Dasypus septemcinctus septemcinctus","Dasypus septemcinctus",
                     gsub("Leopardus tigrinus","Leopardus guttulus",
                                         mamiferos$species))))

mamiferos$family <- gsub("Felídeos","Felidae", mamiferos$family)
```

Remover exóticas/invasoras/domésticas
```{r}
mamiferos <- mamiferos[!grepl("Bos taurus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Callithrix jacchus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Callithrix penicillata", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Canis familiaris", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Felis catus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Lepus capensis", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Lepus europaeus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Rattus norvegicus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Rattus rattus", mamiferos$species),]
mamiferos <- mamiferos[!grepl("Sus scrofa", mamiferos$species),]
```

Pegar o gênero
```{r}
mamiferos$genus <- word(mamiferos$species,1)
```

Checagem
```{r}
unique(sort(mamiferos$species))

unique(sort(mamiferos$genus))

unique(sort(mamiferos$family))

unique(sort(mamiferos$order))
```

Exportar arquivo
```{r}
write.csv(mamiferos, "occ_v_sp.csv")
```

