---
title: "PAN PEQUENOS FELINOS"
subtitle: "Ação 6.1."
author: 'Desenvolvimento: Fernando Lima, D.Sc.'
knit: (function(input, ...) {rmarkdown::render(input, output_dir=paste0(rprojroot::find_rstudio_root_file(), "/02_script/01_limpezaEOrganizacao/outputs/"))})
output:
  pdf_document:
---

Importação de dados (se necessário)

## PREPARAÇÃO

### PACOTES

```{r pacotes, message=FALSE, warning=FALSE}
rm(list = ls(all = TRUE))
source("funcoes/pacotes.R")
pacotes("here", "tidyverse", "httr") #suppdata para burlar captcha mas precisa de instalar RTools
```

### ATLANTIC CAMTRAPS

```{r}
# uma atualização da plataforma adicionou uma barreira contra automação de download. Se houver erro copiar o link e baixar o arquivo manualmente.

download.file(url = "https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecy.1998&file=ecy1998-sup-0001-DataS1.zip",
              destfile = "../01_input/data_papers/atlantic_camtraps.zip",
              mode = "wb"
              )

unzip(
    zipfile = "../01_input/data_papers/atlantic_camtraps.zip",
    exdir = "../01_input/data_papers"
    )
```

### ATLANTIC LARGE MAMMALS

```{r}
# uma atualização da plataforma adicionou uma barreira contra automação de download. Se houver erro copiar o link e baixar o arquivo manualmente.
download.file(url = "https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecy.2785&file=ecy2785-sup-0001-DataS1.zip",
              destfile = "../01_input/data_papers/atlantic_large_mammals.zip",
              mode = "wb"
              )

unzip(
    zipfile = "../01_input/data_papers/atlantic_large_mammals.zip",
    exdir = "../01_input/data_papers"
    )
```

### NEOTROPICAL CARNIVORES

```{r}
# uma atualização da plataforma adicionou uma barreira contra automação de download. Se houver erro copiar o link e baixar o arquivo manualmente.
download.file(url = "https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecy.3128&file=ecy3128-sup-0001-DataS1.zip",
              destfile = "../01_input/data_papers/neotropical_carnivores.zip",
              mode = "wb"
              )

unzip(
    zipfile = "../01_input/data_papers/neotropical_carnivores.zip",
    exdir = "../01_input/data_papers"
    )
```
